version: '3'

services:
  laravel:
    image: luisgcostaguedes/laravel:prod
    container_name: laravel
    networks:
      - laranet

  nginx:
    image: luisgcostaguedes/nginx:prod
    container_name: nginx
    networks:
      - laranet
    ports:
      -"8080:80"
      